version: "3.9"

services:
  api:
    build: .
    container_name: skillpassport-api
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./shared_data:/app/shared_data
      - ./samples:/app/samples
    environment:
      - ENV=dev

  dashboard:
    build: .
    container_name: skillpassport-dashboard
    command: streamlit run frontend/2_Dashboard_Explorer.py --server.address=0.0.0.0 --server.port=8501
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./shared_data:/app/shared_data
      - ./samples:/app/samples
    depends_on:
      - api
